imports:
  # Import default RTE config
  - resource: "EXT:rte_ckeditor/Configuration/RTE/Default.yaml"

editor:
  config:
    removeButtons:
      - Superscript
      - Subscript
      - Indent
      - Outdent

buttons:
  link:
    relAttribute:
      enabled: true
    properties:
      class:
        allowedClasses: link-internal,link-internal-blank,link-download,link-folder,link-external,link-external-blank,link-mail
    page:
      properties:
        class:
          default: link-internal
    file:
      properties:
        class:
          default: link-download
    folder:
      properties:
        class:
          default: link-folder
    url:
      properties:
        class:
          default: link-external-blank
    mail:
      properties:
        class:
          default: link-mail

classesAnchor:
  linkInternal:
    class: link-internal
    type: page
  linkInternalBlank:
    class: link-internal-blank
    type: page
    target: _blank
  linkDownload:
    class: link-download
    type: file
  linkFolder:
    class: link-folder
    type: folder
  linkExternal:
    class: link-external
    type: url
  linkExternalBlank:
    class: link-external-blank
    type: url
    target: _blank
  linkMail:
    class: link-mail
    type: mail
